openapi: 3.0.0
info:
  title: Pdf-converter
  description: Converts pdf-libs JSON output to formio form
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local deployment

paths:
  /pdf/pdf2json:
    post:
      summary: Endpoint for pdf to json converting
      requestBody:
        description: Formdata with file to convert
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                pdf:
                  type: string
                  format: binary
      responses:
        '200':
          description: JSON representation of PDF form fields found in document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Form'
        '400':
          description: Bad request, for example when no file uploaded
        '500':
          description: Internal server error
  /pdf/pdf2html:
    post:
      summary: Endpoint for pdf to html converting
      requestBody:
        description: Formdata with file to convert
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                pdf:
                  type: string
                  format: binary
      responses:
        '200':
          description: HTML representation of PDF document
        '400':
          description: Bad request, for example when no file uploaded
        '500':
          description: Internal server error

components:
  schemas:
    Form:
      type: object
      properties:
        formType:
          type: string
          enum: [NoForm, ArcoForm, XfaForm]
        numPages:
          type: integer
        pages:
          type: array
          items:
            $ref: '#/components/schemas/Page'
    Page:
      type: object
      properties:
        fields:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/TextField'
              - $ref: '#/components/schemas/ButtonField'
              - $ref: '#/components/schemas/RadioButtonField'
              - $ref: '#/components/schemas/ChoiceField'
              - $ref: '#/components/schemas/SignatureField'
    Field:
      type: object
      properties:
        type:
          type: string
          enum: [FormText, FormButton, FormChoice, FormSignature]
        rect:
          $ref: '#/components/schemas/Rect'
        id:
          type: integer
        isVisible:
          type: boolean
        name:
          type: string
        qualifiedName:
          type: string
        uiName:
          type: string

    TextField:
      allOf:
        - $ref: '#/components/schemas/Field'
        - type: object
          properties:
            fontSize:
              type: number
            isPassword:
              type: boolean
            maxLength:
              type: integer
            textAlignment:
              type: string
            textType:
              type: string
              enum: [Normal, Multyline]

    ButtonField:
      allOf:
        - $ref: '#/components/schemas/Field'
        - type: object
          properties:
            buttonType:
              type: string
              enum: [Push, CheckBox, Radio]

    RadioButtonField:
      allOf:
        - $ref: '#/components/schemas/ButtonField'
        - type: object
          properties:
            siblings:
              type: array
              items:
                type: number

    ChoiceField:
      allOf:
        - $ref: '#/components/schemas/Field'
        - type: object
          properties:
            choiceType:
              type: string
              enum: [ComboBox, ListBox]

    SignatureField:
      allOf:
        - $ref: '#/components/schemas/Field'

    Rect:
      type: array
      items:
        type: number
      minItems: 4
      maxItems: 4
